### ISSUE TITLE
nastavit spravny odpocet 

### ISSUE THREAD

**Issue by pjanostak** [Divocaak/vhs-fusionfl#5]
<img width="1145" alt="Screenshot 2024-05-08 at 17 34 11" src="https://github.com/Divocaak/vhs-fusionfl/assets/169270315/f00ac7b0-6888-4ccd-a4ed-10794788b46c">

18.10.2024

neptej se mě kdy má odpočet skončit jinak věřím v tvé moudré zkušenosti :D

**Comment by pjanostak** [comment]
a klidně dejme podkladovou barvu černou což nebo zlatou a upravime pak barvy buttonu 199?

**Comment by Divocaak** [comment]
![Uploading Screenshot 2024-05-08 at 22.20.57.png…]()
